### ISSUE TITLE
Creare un layout e dei parziali

### ISSUE THREAD

**Issue by LucaRanieri96** [LucaRanieri96/laravel-artist#1]
-Crea una cartella "layouts" in views con dentro app.blade.php che servirà da base (layout appunto) della visualizzazione in pagina
-Crea una cartella "partials" con "header.blade.php" e "footer.blade.php" che conterranno i parziali del nostro layout di base
-Crea in views (parallelo a layout e partials) una home.blade.php dove estenderemo il layout e con una "section" inseriremo il contenuto dentro di esso.

**Comment by DamianoCasolari** [comment]
mio

**Comment by LucaRanieri96** [comment]
Ok!
